[package]
name = "polyvalue"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = "1.0.193"
serde_json = "1.0.108"
thiserror = "1.0.50"

[dependencies.fpdec]
version = "0.8.1"
features = ["serde-as-str"]

[dev-dependencies]
version-sync = "0.9.4"
cargo-readme = "3.2.0"